name = "atm-visualizer-server"
main = "src/index.ts"
compatibility_date = "2024-10-18"
compatibility_flags = [ "nodejs_compat" ]

[vars]
JWT_SECRET = "y0uR_s3CR3t_k3Y"
DOMAIN = "localhost"

[[kv_namespaces]]
binding = "KV"
id = "c413d8810d0940f5a7050847631f9b62"
preview_id = "e01d836174534082ba199ba1d2a54de2"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1